{
 "title": "metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total number of HTTP requests in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_received_total[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data traffic in GB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(data_traffic_bytes) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of unsuccessful requests (4xx, 5xx) in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_received_total{code=~\"4.*|5.*\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests with status code 404 in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_received_total{code=\"404\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique visitors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(total_visitors)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total number of successful requests (2xx, 3xx) in the last 24 hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_requests_received_total{code=~\"2.*|3.*\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}