apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-infra-config
data:
  MDB_URL: "mongodb:27017"
  MDB_PORT: "27017"
  DB_SERVER: "mariadb"
  DB_PORT: "3306"
  RMQ_SERVER: "rabbitmq"
  RMQ_PORT: "5672"
  SMTP_HOST: "smtp-relay.sendinblue.com"
  SMTP_PORT: "587"
  GRAFANA_LOKI_URL: "http://loki:3100"
  JAEGER_SERVER: "jaeger"
  JAEGER_PORT: "6831"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-user-service-config
data:
  DB_DATABASE: users_db
  API_PREFIX: userService
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-catalog-service-config
data:
  DB_DATABASE: catalog_db
  API_PREFIX: catalogService
  BOOKING_SERVICE_URL: http://booking-service:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-booking-service-config
data:
  DB_DATABASE: booking_db
  API_PREFIX: bookingService
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-notification-service-config
data:
  MDB_DATABASE: notifications_db
  API_PREFIX: notificationService
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-email-service-config
data:
  MDB_DATABASE: emails_db
  API_PREFIX: emailService
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-realtime-communication-service-config
data:
  API_PREFIX: rtcService
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-image-service-config
data:
  PORT: "80"
  AUTH_HOSTNAME: catalog-service
  AUTH_PORT: "80"
  AUTH_PATH: /api/Accommodations/can-modify/
