apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-service
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        network/application: "true"
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: ftripio/frontend-service-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
