apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        network/monitoring: "true"
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.45
          resources:
            requests:
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6831
            - containerPort: 16686
            - containerPort: 14269
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jaeger
  ports:
    - name: default
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: another
      port: 16686
      targetPort: 16686
    - name: metrics
      port: 14269
      targetPort: 14269
