apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog-service
  name: catalog-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: catalog-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog-service
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        network/application: "true"
        network/monitoring: "true"
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ftripio/catalog-service-dev
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 80
          env:
            - name: API_PROXY_URL
              value: ftripio.isobarot.com
            - name: HEALTH_CHECK_BASE_PATH
              value: http://catalog-service:80
            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: API_PREFIX
                  name: ftrip-io-catalog-service-config
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ftrip-io-catalog-service-config
                  key: DB_DATABASE
            - name: BOOKING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ftrip-io-catalog-service-config
                  key: BOOKING_SERVICE_URL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: ftrip-io-infra-secrets
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: ftrip-io-infra-config
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER
                  name: ftrip-io-infra-config
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: ftrip-io-infra-secrets
            - name: GRAFANA_LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: GRAFANA_LOKI_URL
                  name: ftrip-io-infra-config
            - name: JAEGER_PORT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_PORT
                  name: ftrip-io-infra-config
            - name: JAEGER_SERVER
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_SERVER
                  name: ftrip-io-infra-config
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: ftrip-io-infra-secrets
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RMQ_PASSWORD
                  name: ftrip-io-infra-secrets
            - name: RMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RMQ_PORT
                  name: ftrip-io-infra-config
            - name: RMQ_SERVER
              valueFrom:
                configMapKeyRef:
                  key: RMQ_SERVER
                  name: ftrip-io-infra-config
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  key: RMQ_USER
                  name: ftrip-io-infra-secrets
          resources: {{- toYaml .Values.resources | nindent 12 }}
