apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-service
  name: email-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: email-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email-service
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        network/application: "true"
        network/monitoring: "true"
        app: email-service
    spec:
      containers:
        - name: email-service
          image: ftripio/email-service-dev
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 80
          env:
            - name: API_PROXY_URL
              value: ftripio.isobarot.com
            - name: HEALTH_CHECK_BASE_PATH
              value: http://email-service:80
            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: API_PREFIX
                  name: ftrip-io-email-service-config
            - name: MDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ftrip-io-email-service-config
                  key: MDB_DATABASE
            - name: GRAFANA_LOKI_URL
              valueFrom:
                configMapKeyRef:
                  key: GRAFANA_LOKI_URL
                  name: ftrip-io-infra-config
            - name: JAEGER_PORT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_PORT
                  name: ftrip-io-infra-config
            - name: JAEGER_SERVER
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_SERVER
                  name: ftrip-io-infra-config
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: ftrip-io-infra-secrets
            - name: MDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MDB_PASSWORD
                  name: ftrip-io-infra-secrets
            - name: MDB_PORT
              valueFrom:
                configMapKeyRef:
                  key: MDB_PORT
                  name: ftrip-io-infra-config
            - name: MDB_URL
              valueFrom:
                configMapKeyRef:
                  key: MDB_URL
                  name: ftrip-io-infra-config
            - name: MDB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MDB_USERNAME
                  name: ftrip-io-infra-secrets
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RMQ_PASSWORD
                  name: ftrip-io-infra-secrets
            - name: RMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RMQ_PORT
                  name: ftrip-io-infra-config
            - name: RMQ_SERVER
              valueFrom:
                configMapKeyRef:
                  key: RMQ_SERVER
                  name: ftrip-io-infra-config
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  key: RMQ_USER
                  name: ftrip-io-infra-secrets
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  key: SMTP_HOST
                  name: ftrip-io-infra-config
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SMTP_PASSWORD
                  name: ftrip-io-infra-secrets
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: SMTP_PORT
                  name: ftrip-io-infra-config
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SMTP_USERNAME
                  name: ftrip-io-infra-secrets
          resources: {{- toYaml .Values.resources | nindent 12 }}
