apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
  name: loki
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        network/application: "true"
        network/monitoring: "true"
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:main-5206e3a
          imagePullPolicy: Always
          ports:
            - containerPort: 3100
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
