
version: "3.8"

services:
  mongo:
    image: mongo:4.2.23
    restart: always
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGODB_USERNAME -p $MONGODB_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ftripio
    ports:
      - ${MONGODB_PORT}:27017


  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    profiles:
      - dev
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:${MONGODB_PORT}
    networks:
      - ftripio
    depends_on:
      mongo:
        condition: service_healthy

  mariadb:
    image: mariadb:10.7.8-focal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ftripio
    volumes:
      - ./maria-db-data:/var/lib/mysql
    networks:
      - ftripio
    ports:
      - ${DB_PORT}:3306

  adminer:
    image: adminer:4.8.1-standalone
    profiles:
      - dev
    restart: always
    networks:
      - ftripio
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    networks:
      - ftripio
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  playground-service:
    image: ftrip.io/playground-service
    restart: always
    networks:
      - ftripio
    ports: 
      - 5000:80
    environment:
      JWT_SECRET: ${JWT_SECRET}

      MDB_URL: mongo:${MONGODB_PORT}
      MDB_USERNAME: ${MONGODB_USERNAME}
      MDB_PASSWORD: ${MONGODB_PASSWORD}
      MDB_DATABASE: ${PS_MDB_DATABASE}

      DB_SERVER: mariadb
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${PS_MDB_DATABASE}

      RMQ_SERVER: rabbitmq
      RMQ_PORT: 5672
      RMQ_USER: ${RMQ_USER}
      RMQ_PASSWORD: ${RMQ_PASSWORD}

      API_PREFIX: ${PS_API_PREFIX}
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      # mariadb: mariadb

  http-proxy:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ftripio
    ports:
      - 3000:80
    depends_on:
      - playground-service

networks:
  ftripio:
    name: ftripio
    driver: bridge
