apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-infra-config
data:
  MDB_URL: "mongodb:27017"
  MDB_PORT: "27017"
  DB_SERVER: "mariadb"
  DB_PORT: "3306"
  RMQ_SERVER: "rabbitmq"
  RMQ_PORT: "5672"
  SMTP_HOST: "smtp-relay.sendinblue.com"
  SMTP_PORT: "587"
  GRAFANA_LOKI_URL: "http://loki:3100"
  JAEGER_SERVER: "jaeger"
  JAEGER_PORT: "6831"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftrip-io-rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus].